
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "../ext/src/window/MessageBox.js",
  "overrides.TabCloseMenu": "overrides/TabCloseMenu.js",
  "overrides": "../packages/my-custom-theme/overrides",
  "Ext": "../ext/src",
  "overrides.RowExpander": "overrides/RowExpander.js",
  "Zixweb": "app",
  "Ext.rtl.EventObjectImpl": "../ext/src/rtl/EventObject.js",
  "overrides.VType": "overrides/VType.js",
  "overrides.Date": "overrides/Date.js",
  "overrides.Table": "overrides/Table.js",
  "Zixweb.Application": "app/application.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "overrides.grid.RowEditor": [],
  "Zixweb.view.component.Product": [],
  "Zixweb.view.Viewport": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "overrides.layout.component.Dock": [],
  "Zixweb.view.component.ZyzjAcct": [],
  "Zixweb.view.component.Bi": [],
  "Zixweb.view.component.YsType": [],
  "Zixweb.view.pzlr.i0000": [],
  "Zixweb.view.component.Routes": [],
  "Zixweb.controller.Index": [],
  "Zixweb.controller.Task": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "Zixweb.view.book.hist.fee_jrjg": [],
  "Zixweb.view.book.hist.cost_bfee": [],
  "Zixweb.view.role.List": [],
  "Ext.ux.DataView.DragSelector": [],
  "Zixweb.store.component.MStatus": [],
  "Zixweb.store.component.JStatus": [],
  "Zixweb.view.book.hist.cost_in": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Zixweb.store.component.Status": [],
  "Zixweb.view.book.hist.income_cfee": [],
  "overrides.RowExpander": [],
  "Zixweb.controller.Login": [],
  "Zixweb.controller.Pzlr": [],
  "Zixweb.store.component.Acct": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Zixweb.view.Center": [],
  "Zixweb.view.South": [],
  "Zixweb.view.user.Add": [],
  "Ext.ux.PreviewPlugin": [],
  "Zixweb.view.component.SHType": [],
  "overrides.toolbar.Paging": [],
  "Zixweb.view.pzlr.mission": [],
  "Ext.ux.ajax.SimXhr": [],
  "Zixweb.view.book.detail.cost_in": [],
  "Ext.ux.event.RecorderManager": [],
  "Zixweb.view.book.detail.income_zhlx": [],
  "Zixweb.view.component.Acct": [],
  "Zixweb.controller.Main": [],
  "Zixweb.view.book.detail.bfj_cust": [],
  "Zixweb.view.book.detail.cost_dfss": [],
  "Zixweb.view.component.ZjbdType": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Zixweb.view.zqqr.query": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Zixweb.store.component.BfjAcct": [],
  "Zixweb.store.component.Product": [],
  "Ext.ux.TabReorderer": [],
  "Zixweb.view.book.detail.cost_bfee": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "overrides.resizer.Splitter": [],
  "Ext.ux.event.Recorder": [],
  "Zixweb.view.user.Edit": [],
  "overrides.TabCloseMenu": [],
  "overrides.Component": [],
  "Zixweb.view.book.hist.bamt_yhyf": [],
  "Ext.ux.ajax.SimManager": [],
  "Zixweb.view.pzlr.job": [],
  "Zixweb.view.book.hist.income_in": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Zixweb.view.component.HSX": [],
  "Zixweb.view.user.List": [],
  "Zixweb.controller.Component": [],
  "Ext.ux.TabScrollerMenu": [],
  "Zixweb.view.login.PasswordReset": [],
  "Zixweb.view.book.detail.fee_jrjg": [],
  "Zixweb.view.book.ZyzjBooks": [],
  "Zixweb.controller.Routes": [],
  "Ext.ux.IFrame": [],
  "Zixweb.view.component.MStatus": [],
  "overrides.Date": [],
  "Zixweb.view.book.detail.income_in": [],
  "Ext.ux.form.SearchField": [],
  "Zixweb.view.book.hist.txamt_dqr_byf": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Zixweb.view.book.detail.bamt_yhyf": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "Zixweb.controller.Users": [],
  "Zixweb.view.book.detail.bfee_yhyf": [],
  "Zixweb.view.component.Status": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "overrides.toolbar.Toolbar": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Zixweb.view.task.Taskmy": [],
  "Zixweb.view.yspz.yspzq.Detail": [],
  "overrides.form.field.HtmlEditor": [],
  "Zixweb.view.component.BfjAcct": [],
  "Zixweb.view.component.Books": [],
  "Ext.ux.FieldReplicator": [],
  "overrides.grid.column.RowNumberer": [],
  "Zixweb.view.role.Edit": [],
  "Zixweb.view.West": [],
  "Zixweb.view.component.SHStatus": [],
  "Zixweb.view.zjdz.bfjgzcx": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Zixweb.view.book.hist.cost_dfss": [],
  "Zixweb.store.component.YsType": [],
  "Zixweb.view.yspz.revoke_cause": [],
  "Zixweb.view.book.detail.income_cfee": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "overrides.panel.Table": [],
  "Zixweb.view.book.BfjBooks": [],
  "Zixweb.view.role.Add": [],
  "Zixweb.view.login.LoginForm": [],
  "Zixweb.view.book.detail.deposit_bfj": [],
  "Zixweb.view.zqqr.submit": [],
  "Zixweb.view.book.hist.income_zhlx": [],
  "Zixweb.controller.Roles": [],
  "Ext.ux.GMapPanel": [],
  "Zixweb.controller.Yspz": [],
  "Zixweb.view.task.Task0000": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Zixweb.store.component.ZQQRStatus": [],
  "Zixweb.view.Main": [],
  "Zixweb.view.zjdz.bfj": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "overrides.panel.Panel": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.DataView.Animated": [],
  "Zixweb.view.book.detail.txamt_yhyf": [],
  "Zixweb.store.component.Bi": [],
  "Zixweb.Application": [],
  "Zixweb.store.component.ZyzjAcct": [],
  "Zixweb.view.book.detail.cost_bfee_zg": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Zixweb.store.component.Books": [],
  "Zixweb.view.login.Logout": [],
  "overrides.container.ButtonGroup": [],
  "Zixweb.controller.Books": [],
  "Zixweb.view.book.AllBooks": [],
  "overrides.panel.Tool": [],
  "Zixweb.view.book.hist.cost_bfee_zg": [],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Zixweb.store.component.Routes": [],
  "Zixweb.view.book.hist.deposit_bfj": [],
  "Ext.ux.event.Player": [],
  "Zixweb.controller.Zjdz": [],
  "overrides.menu.Menu": [],
  "Zixweb.view.North": [],
  "Zixweb.view.task.Taskpzcxdetail": [],
  "Zixweb.store.component.ZjbdType": [],
  "Ext.ux.ToolbarDroppable": [],
  "Zixweb.view.zjdz.bfjdetail": [],
  "Ext.ux.event.Maker": [],
  "Zixweb.view.task.Task0000detail": [],
  "overrides.menu.Separator": [],
  "Zixweb.view.book.detail.txamt_dqr_byf": [],
  "Zixweb.controller.Zqqr": [],
  "Ext.ux.DataView.Draggable": [],
  "overrides.picker.Month": [],
  "Ext.ux.TabCloseMenu": [],
  "overrides.VType": [],
  "Zixweb.view.book.hist.bfj_cust": [],
  "Ext.ux.DataTip": [],
  "Zixweb.view.book.hist.bfee_yhyf": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Zixweb.view.component.ZQQRStatus": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Zixweb.view.book.hist.txamt_yhyf": [],
  "Ext.ux.grid.FiltersFeature": [],
  "overrides.tab.Tab": [],
  "Zixweb.view.task.Taskpzcx": []
});
Ext.ClassManager.addNameAliasMappings({
  "overrides.grid.RowEditor": [],
  "Zixweb.view.component.Product": [
    "widget.product"
  ],
  "Zixweb.view.Viewport": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "overrides.layout.component.Dock": [],
  "Zixweb.view.component.ZyzjAcct": [
    "widget.zyzjacct"
  ],
  "Zixweb.view.component.Bi": [
    "widget.bi"
  ],
  "Zixweb.view.component.YsType": [
    "widget.ystype"
  ],
  "Zixweb.view.pzlr.i0000": [
    "widget.i0000"
  ],
  "Zixweb.view.component.Routes": [
    "widget.routes"
  ],
  "Zixweb.controller.Index": [],
  "Zixweb.controller.Task": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "Zixweb.view.book.hist.fee_jrjg": [
    "widget.book_hist_fee_jrjg"
  ],
  "Zixweb.view.book.hist.cost_bfee": [
    "widget.book_hist_cost_bfee"
  ],
  "Zixweb.view.role.List": [
    "widget.rolelist"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Zixweb.store.component.MStatus": [],
  "Zixweb.store.component.JStatus": [],
  "Zixweb.view.book.hist.cost_in": [
    "widget.book_hist_cost_in"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Zixweb.store.component.Status": [],
  "Zixweb.view.book.hist.income_cfee": [
    "widget.book_hist_income_cfee"
  ],
  "overrides.RowExpander": [],
  "Zixweb.controller.Login": [],
  "Zixweb.controller.Pzlr": [],
  "Zixweb.store.component.Acct": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Zixweb.view.Center": [
    "widget.center"
  ],
  "Zixweb.view.South": [
    "widget.south"
  ],
  "Zixweb.view.user.Add": [
    "widget.useradd"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Zixweb.view.component.SHType": [
    "widget.shtype"
  ],
  "overrides.toolbar.Paging": [],
  "Zixweb.view.pzlr.mission": [
    "widget.pzlrmission"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Zixweb.view.book.detail.cost_in": [
    "widget.book_detail_cost_in"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Zixweb.view.book.detail.income_zhlx": [
    "widget.book_detail_income_zhlx"
  ],
  "Zixweb.view.component.Acct": [
    "widget.acct"
  ],
  "Zixweb.controller.Main": [],
  "Zixweb.view.book.detail.bfj_cust": [
    "widget.book_detail_bfj_cust"
  ],
  "Zixweb.view.book.detail.cost_dfss": [
    "widget.book_detail_cost_dfss"
  ],
  "Zixweb.view.component.ZjbdType": [
    "widget.zjbdtype"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Zixweb.view.zqqr.query": [
    "widget.zqqrquery"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Zixweb.store.component.BfjAcct": [],
  "Zixweb.store.component.Product": [],
  "Ext.ux.TabReorderer": [],
  "Zixweb.view.book.detail.cost_bfee": [
    "widget.book_detail_cost_bfee"
  ],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "overrides.resizer.Splitter": [],
  "Ext.ux.event.Recorder": [],
  "Zixweb.view.user.Edit": [
    "widget.useredit"
  ],
  "overrides.TabCloseMenu": [],
  "overrides.Component": [],
  "Zixweb.view.book.hist.bamt_yhyf": [
    "widget.book_hist_bamt_yhyf"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Zixweb.view.pzlr.job": [
    "widget.pzlrjob"
  ],
  "Zixweb.view.book.hist.income_in": [
    "widget.book_hist_income_in"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Zixweb.view.component.HSX": [
    "widget.hsx"
  ],
  "Zixweb.view.user.List": [
    "widget.userlist"
  ],
  "Zixweb.controller.Component": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Zixweb.view.login.PasswordReset": [
    "widget.passwordreset"
  ],
  "Zixweb.view.book.detail.fee_jrjg": [
    "widget.book_detail_fee_jrjg"
  ],
  "Zixweb.view.book.ZyzjBooks": [
    "widget.bookzyzj"
  ],
  "Zixweb.controller.Routes": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Zixweb.view.component.MStatus": [
    "widget.mstatus"
  ],
  "overrides.Date": [],
  "Zixweb.view.book.detail.income_in": [
    "widget.book_detail_income_in"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Zixweb.view.book.hist.txamt_dqr_byf": [
    "widget.book_hist_txamt_dqr_byf"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Zixweb.view.book.detail.bamt_yhyf": [
    "widget.book_detail_bamt_yhyf"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Zixweb.controller.Users": [],
  "Zixweb.view.book.detail.bfee_yhyf": [
    "widget.book_detail_bfee_yhyf"
  ],
  "Zixweb.view.component.Status": [
    "widget.status"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "overrides.toolbar.Toolbar": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Zixweb.view.task.Taskmy": [
    "widget.taskmy"
  ],
  "Zixweb.view.yspz.yspzq.Detail": [
    "widget.yspzqdetail"
  ],
  "overrides.form.field.HtmlEditor": [],
  "Zixweb.view.component.BfjAcct": [
    "widget.bfjacct"
  ],
  "Zixweb.view.component.Books": [
    "widget.books"
  ],
  "Ext.ux.FieldReplicator": [],
  "overrides.grid.column.RowNumberer": [],
  "Zixweb.view.role.Edit": [
    "widget.roledit"
  ],
  "Zixweb.view.West": [
    "widget.west"
  ],
  "Zixweb.view.component.SHStatus": [
    "widget.shstatus"
  ],
  "Zixweb.view.zjdz.bfjgzcx": [
    "widget.zjdzbfjgzcx"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Zixweb.view.book.hist.cost_dfss": [
    "widget.book_hist_cost_dfss"
  ],
  "Zixweb.store.component.YsType": [],
  "Zixweb.view.yspz.revoke_cause": [
    "widget.yspzrevoke_cause"
  ],
  "Zixweb.view.book.detail.income_cfee": [
    "widget.book_detail_income_cfee"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "overrides.panel.Table": [],
  "Zixweb.view.book.BfjBooks": [
    "widget.bookbfj"
  ],
  "Zixweb.view.role.Add": [
    "widget.roleadd"
  ],
  "Zixweb.view.login.LoginForm": [
    "widget.loginform"
  ],
  "Zixweb.view.book.detail.deposit_bfj": [
    "widget.book_detail_deposit_bfj"
  ],
  "Zixweb.view.zqqr.submit": [
    "widget.zqqrsubmit"
  ],
  "Zixweb.view.book.hist.income_zhlx": [
    "widget.book_hist_income_zhlx"
  ],
  "Zixweb.controller.Roles": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Zixweb.controller.Yspz": [],
  "Zixweb.view.task.Task0000": [
    "widget.task0000"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Zixweb.store.component.ZQQRStatus": [],
  "Zixweb.view.Main": [
    "widget.app-main"
  ],
  "Zixweb.view.zjdz.bfj": [
    "widget.zjdzbfj"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "overrides.panel.Panel": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.DataView.Animated": [],
  "Zixweb.view.book.detail.txamt_yhyf": [
    "widget.book_detail_txamt_yhyf"
  ],
  "Zixweb.store.component.Bi": [],
  "Zixweb.Application": [],
  "Zixweb.store.component.ZyzjAcct": [],
  "Zixweb.view.book.detail.cost_bfee_zg": [
    "widget.book_detail_cost_bfee_zg"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Zixweb.store.component.Books": [],
  "Zixweb.view.login.Logout": [
    "widget.logout"
  ],
  "overrides.container.ButtonGroup": [],
  "Zixweb.controller.Books": [],
  "Zixweb.view.book.AllBooks": [
    "widget.bookall"
  ],
  "overrides.panel.Tool": [],
  "Zixweb.view.book.hist.cost_bfee_zg": [
    "widget.book_hist_cost_bfee_zg"
  ],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Zixweb.store.component.Routes": [],
  "Zixweb.view.book.hist.deposit_bfj": [
    "widget.book_hist_deposit_bfj"
  ],
  "Ext.ux.event.Player": [],
  "Zixweb.controller.Zjdz": [],
  "overrides.menu.Menu": [],
  "Zixweb.view.North": [
    "widget.north"
  ],
  "Zixweb.view.task.Taskpzcxdetail": [
    "widget.taskpzcxdetail"
  ],
  "Zixweb.store.component.ZjbdType": [],
  "Ext.ux.ToolbarDroppable": [],
  "Zixweb.view.zjdz.bfjdetail": [
    "widget.zjdzbfjdetail"
  ],
  "Ext.ux.event.Maker": [],
  "Zixweb.view.task.Task0000detail": [
    "widget.task0000detail"
  ],
  "overrides.menu.Separator": [],
  "Zixweb.view.book.detail.txamt_dqr_byf": [
    "widget.book_detail_txamt_dqr_byf"
  ],
  "Zixweb.controller.Zqqr": [],
  "Ext.ux.DataView.Draggable": [],
  "overrides.picker.Month": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "overrides.VType": [],
  "Zixweb.view.book.hist.bfj_cust": [
    "widget.book_hist_bfj_cust"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Zixweb.view.book.hist.bfee_yhyf": [
    "widget.book_hist_bfee_yhyf"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Zixweb.view.component.ZQQRStatus": [
    "widget.zqqrstatus"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Zixweb.view.book.hist.txamt_yhyf": [
    "widget.book_hist_txamt_yhyf"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "overrides.tab.Tab": [],
  "Zixweb.view.task.Taskpzcx": [
    "widget.taskpzcx"
  ]
});
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/Component.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/panel/Panel.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/layout/component/Dock.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/toolbar/Toolbar.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/container/ButtonGroup.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/toolbar/Paging.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/picker/Month.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/form/field/HtmlEditor.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/panel/Table.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/grid/RowEditor.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/grid/column/RowNumberer.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/resizer/Splitter.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/menu/Menu.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/menu/Separator.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/panel/Tool.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/tab/Tab.js");
