
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "overrides.DateField": "overrides/DateField.js",
  "overrides": "../packages/my-custom-theme/overrides",
  "overrides.Treepanel": "overrides/Treepanel.js",
  "overrides.RowExpander": "overrides/RowExpander.js",
  "Zixweb": "app",
  "overrides.Ext": "overrides/Ext.js",
  "Ext.rtl.EventObjectImpl": "../ext/src/rtl/EventObject.js",
  "overrides.VType": "overrides/VType.js",
  "overrides.Table": "overrides/Table.js",
  "overrides.Gridpanel": "overrides/Gridpanel.js",
  "overrides.Date": "overrides/Date.js",
  " Ext.Msg": "../ext/src/window/MessageBox.js",
  "overrides.TabCloseMenu": "overrides/TabCloseMenu.js",
  "Ext": "../ext/src",
  "overrides.HBox": "overrides/HBox.js",
  "overrides.Paging": "overrides/Paging.js",
  "overrides.Format": "overrides/Format.js",
  "Zixweb.Application": "app/application.js",
  "overrides.Connection": "overrides/Connection.js",
  "Zixweb.view.component.base.TextField": "app/view/component/base/TextFiled.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Zixweb.view.zjdz.bfjacctmemo": [],
  "Zixweb.store.acct": [],
  "overrides.layout.component.Dock": [],
  "Zixweb.view.component.flag": [],
  "Zixweb.view.component.YsType": [],
  "Zixweb.view.yspz.Panel": [],
  "overrides.Paging": [],
  "Zixweb.view.component.base.Number": [],
  "Ext.ux.DataView.DragSelector": [],
  "Zixweb.view.role.List": [],
  "Zixweb.store.ZQQRStatus": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Zixweb.view.component.hsx.ftx_date": [],
  "Zixweb.store.RStatus": [],
  "overrides.RowExpander": [],
  "overrides.Ext": [],
  "Zixweb.controller.Pzlr": [],
  "Zixweb.store.fhyd_acct": [],
  "Zixweb.view.South": [],
  "Ext.ux.PreviewPlugin": [],
  "Zixweb.view.component.hsx.zyzj_acct": [],
  "Ext.ux.ajax.SimXhr": [],
  "Zixweb.view.component.hsx.f_ssn": [],
  "Ext.ux.CellDragDrop": [],
  "Zixweb.view.zqqr.query": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "overrides.Gridpanel": [],
  "Zixweb.view.jcsjwh.bfjacct.Edit": [],
  "Zixweb.view.zjdz.fypdetail": [],
  "Ext.ux.event.Recorder": [],
  "Zixweb.view.user.Edit": [],
  "Zixweb.store.JStatus": [],
  "Zixweb.view.component.hsx.yw_type": [],
  "Zixweb.view.pzlr.job": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Zixweb.view.component.HSX": [],
  "Zixweb.view.component.d": [],
  "Zixweb.view.component.AcctStatus": [],
  "Zixweb.controller.Component": [],
  "Zixweb.view.component.hsx.fe_date": [],
  "Zixweb.view.component.hsx.fyp_acct": [],
  "Ext.ux.IFrame": [],
  "Zixweb.view.book.ZyzjBooks": [],
  "Zixweb.view.task.TaskFpzcx": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Zixweb.controller.Users": [],
  "Zixweb.view.component.period": [],
  "overrides.Format": [],
  "Zixweb.view.component.Status": [],
  "Zixweb.view.component.j": [],
  "Zixweb.view.zjdz.fyp": [],
  "Zixweb.view.task.Taskmy": [],
  "Ext.ux.FieldReplicator": [],
  "Zixweb.view.component.Books": [],
  "overrides.grid.column.RowNumberer": [],
  "Zixweb.store.fyp_acct": [],
  "Zixweb.view.component.hsx.fyw_type": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Zixweb.view.task.TaskF0000": [],
  "Zixweb.view.yspz.revoke_cause": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "overrides.panel.Table": [],
  "Zixweb.view.login.LoginForm": [],
  "Zixweb.view.task.TaskF0000detail": [],
  "Ext.ux.GMapPanel": [],
  "Zixweb.controller.Roles": [],
  "Zixweb.controller.Yspz": [],
  "Ext.ux.GroupTabPanel": [],
  "Zixweb.view.zjdz.bfj": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Zixweb.store.fhw_type": [],
  "overrides.panel.Panel": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.DataView.Animated": [],
  "overrides.DateField": [],
  "Zixweb.view.component.hsx.e_date": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Zixweb.view.component.ts_revoke": [],
  "Zixweb.view.component.hsx.zjbd_date": [],
  "Zixweb.controller.Books": [],
  "Zixweb.store.p": [],
  "Zixweb.view.book.AllBooks": [],
  "Zixweb.view.component.hsx.tx_date": [],
  "Zixweb.view.Panel": [],
  "Zixweb.view.component.hsx.fch": [],
  "Ext.ux.event.Player": [],
  "overrides.Connection": [],
  "Ext.ux.ToolbarDroppable": [],
  "Zixweb.view.zjdz.bfjdetail": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Zixweb.view.pzlr.i0101": [],
  "Zixweb.view.book.BookPanel": [],
  "Zixweb.view.component.hsx.bfj_acct": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Zixweb.view.jcsjwh.bfjacct.List": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "overrides.HBox": [],
  "overrides.tab.Tab": [],
  "overrides.grid.RowEditor": [],
  "overrides.Treepanel": [],
  "Zixweb.view.task.TaskFmy": [],
  "Zixweb.view.component.base.Money": [],
  "Zixweb.view.Viewport": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Zixweb.view.component.hsx.bi": [],
  "Zixweb.view.jcsjwh.bfjacct.Add": [],
  "Zixweb.view.pzlr.i0000": [],
  "Zixweb.view.component.Routes": [],
  "Zixweb.controller.Index": [],
  "Zixweb.view.component.Fields": [],
  "Zixweb.controller.Task": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Zixweb.view.pzlr.i0149": [],
  "Zixweb.store.wlzj_type": [],
  "Zixweb.view.pzlr.i0148": [],
  "Zixweb.store.CBase": [],
  "Zixweb.view.component.hsx.period": [],
  "Zixweb.view.component.base.TextField": [],
  "Zixweb.controller.Login": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Zixweb.view.component.base.DateField": [],
  "Zixweb.view.Center": [],
  "Zixweb.view.user.Add": [],
  "Zixweb.store.zyzj_acct": [],
  "Zixweb.view.component.hsx.fhw_type": [],
  "Zixweb.view.component.SHType": [],
  "overrides.toolbar.Paging": [],
  "Zixweb.view.component.hsx.fcg_date": [],
  "Zixweb.view.pzlr.mission": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Zixweb.view.component.YSID": [],
  "Zixweb.view.yspz.Detail": [],
  "overrides.resizer.Splitter": [],
  "overrides.Component": [],
  "overrides.TabCloseMenu": [],
  "Zixweb.view.pzlr.f0000": [],
  "Ext.ux.ajax.SimManager": [],
  "Zixweb.view.component.hsx.f_agm": [],
  "Zixweb.store.MStatus": [],
  "Zixweb.view.user.List": [],
  "Zixweb.store.Status": [],
  "Zixweb.view.login.PasswordReset": [],
  "Ext.ux.TabScrollerMenu": [],
  "Zixweb.view.zjdz.qddetail": [],
  "Zixweb.controller.Routes": [],
  "Zixweb.view.component.revoke_user": [],
  "Zixweb.view.component.MStatus": [],
  "overrides.Date": [],
  "Zixweb.view.component.base.QueryForm": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Zixweb.view.pzlr.i0015": [],
  "Zixweb.view.pzlr.i0014": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Zixweb.view.component.base.MoneyField": [],
  "Ext.ux.TreePicker": [],
  "Zixweb.store.fyw_type": [],
  "Zixweb.view.component.hsx.acct": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Zixweb.view.pzlr.i0018": [],
  "overrides.toolbar.Toolbar": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Zixweb.view.component.hsx.fm": [],
  "Ext.ux.GroupTabRenderer": [],
  "Zixweb.view.component.hsx.zjbd_type": [],
  "overrides.form.field.HtmlEditor": [],
  "Zixweb.view.component.hsx.fc": [],
  "Zixweb.store.YsType": [],
  "Zixweb.view.task.TaskFpzcxdetail": [],
  "Zixweb.view.zjdz.qd": [],
  "Zixweb.view.West": [],
  "Zixweb.view.role.Edit": [],
  "Zixweb.store.bi": [],
  "Zixweb.view.component.SHStatus": [],
  "Zixweb.view.zjdz.bfjgzcx": [],
  "Zixweb.view.component.ExportBtn": [],
  "Zixweb.view.component.base.MyStore": [],
  "Zixweb.view.component.hsx.wlzj_type": [],
  "Zixweb.view.book.BfjBooks": [],
  "Zixweb.view.role.Add": [],
  "Zixweb.view.zqqr.submit": [],
  "Zixweb.view.task.Task0000": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Zixweb.controller.Jcsjwh": [],
  "Zixweb.view.book.FhydBooks": [],
  "Zixweb.Application": [],
  "Zixweb.view.zjdz.bfjresult": [],
  "Zixweb.view.component.hsx.p": [],
  "Zixweb.view.book.DetailPanel": [],
  "overrides.container.ButtonGroup": [],
  "overrides.panel.Tool": [],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Zixweb.view.component.ID": [],
  "Ext.ux.RowExpander": [],
  "Zixweb.store.zjbd_type": [],
  "Zixweb.view.component.hsx.c": [],
  "Zixweb.controller.Zjdz": [],
  "Zixweb.view.component.base.ComboBox": [],
  "Zixweb.view.North": [],
  "overrides.menu.Menu": [],
  "Zixweb.view.task.Taskpzcxdetail": [],
  "Zixweb.view.component.plugins.PageComboResizer": [],
  "Zixweb.store.bfj_acct": [],
  "Ext.ux.event.Maker": [],
  "Zixweb.view.component.hsx.f_dcn": [],
  "Zixweb.view.task.Task0000detail": [],
  "overrides.menu.Separator": [],
  "Zixweb.view.component.hsx.fhyd_acct": [],
  "Zixweb.controller.Zqqr": [],
  "overrides.picker.Month": [],
  "overrides.VType": [],
  "Zixweb.view.book.SumPanel": [],
  "Zixweb.view.component.crt_user": [],
  "Ext.ux.DataTip": [],
  "Zixweb.view.component.ZQQRStatus": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Zixweb.view.component.hsx.fp": [],
  "Zixweb.view.task.Taskpzcx": [],
  "Zixweb.view.component.hsx.cust_proto": []
});
Ext.ClassManager.addNameAliasMappings({
  "Zixweb.view.zjdz.bfjacctmemo": [
    "widget.bfjacctmemo"
  ],
  "Zixweb.store.acct": [],
  "overrides.layout.component.Dock": [],
  "Zixweb.view.component.flag": [
    "widget.flag",
    "widget.rstatus"
  ],
  "Zixweb.view.component.YsType": [
    "widget.ys_type",
    "widget.ystype"
  ],
  "Zixweb.view.yspz.Panel": [],
  "overrides.Paging": [],
  "Zixweb.view.component.base.Number": [],
  "Ext.ux.DataView.DragSelector": [],
  "Zixweb.view.role.List": [
    "widget.rolelist"
  ],
  "Zixweb.store.ZQQRStatus": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Zixweb.view.component.hsx.ftx_date": [
    "widget.ftx_date"
  ],
  "Zixweb.store.RStatus": [],
  "overrides.RowExpander": [],
  "overrides.Ext": [],
  "Zixweb.controller.Pzlr": [],
  "Zixweb.store.fhyd_acct": [],
  "Zixweb.view.South": [
    "widget.south"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Zixweb.view.component.hsx.zyzj_acct": [
    "widget.zyzj_acct",
    "widget.zyzjacct"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Zixweb.view.component.hsx.f_ssn": [
    "widget.f_ssn"
  ],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Zixweb.view.zqqr.query": [
    "widget.zqqrquery"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "overrides.Gridpanel": [],
  "Zixweb.view.jcsjwh.bfjacct.Edit": [
    "widget.bfjacctedit"
  ],
  "Zixweb.view.zjdz.fypdetail": [
    "widget.zjdzfypdetail"
  ],
  "Ext.ux.event.Recorder": [],
  "Zixweb.view.user.Edit": [
    "widget.useredit"
  ],
  "Zixweb.store.JStatus": [],
  "Zixweb.view.component.hsx.yw_type": [
    "widget.yw_type"
  ],
  "Zixweb.view.pzlr.job": [
    "widget.pzlrjob"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Zixweb.view.component.HSX": [
    "widget.hsx"
  ],
  "Zixweb.view.component.d": [
    "widget.d_amt"
  ],
  "Zixweb.view.component.AcctStatus": [
    "widget.acctStatus"
  ],
  "Zixweb.controller.Component": [],
  "Zixweb.view.component.hsx.fe_date": [
    "widget.fe_date"
  ],
  "Zixweb.view.component.hsx.fyp_acct": [
    "widget.fyp_acct"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Zixweb.view.book.ZyzjBooks": [
    "widget.bookzyzj"
  ],
  "Zixweb.view.task.TaskFpzcx": [
    "widget.taskfpzcx"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Zixweb.controller.Users": [],
  "Zixweb.view.component.period": [
    "widget.period_"
  ],
  "overrides.Format": [],
  "Zixweb.view.component.Status": [
    "widget.status"
  ],
  "Zixweb.view.component.j": [
    "widget.j_amt"
  ],
  "Zixweb.view.zjdz.fyp": [
    "widget.zjdzfyp"
  ],
  "Zixweb.view.task.Taskmy": [
    "widget.taskmy"
  ],
  "Ext.ux.FieldReplicator": [],
  "Zixweb.view.component.Books": [
    "widget.books"
  ],
  "overrides.grid.column.RowNumberer": [],
  "Zixweb.store.fyp_acct": [],
  "Zixweb.view.component.hsx.fyw_type": [
    "widget.fyw_type"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Zixweb.view.task.TaskF0000": [
    "widget.taskf0000"
  ],
  "Zixweb.view.yspz.revoke_cause": [
    "widget.yspzrevoke_cause"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "overrides.panel.Table": [],
  "Zixweb.view.login.LoginForm": [
    "widget.loginform"
  ],
  "Zixweb.view.task.TaskF0000detail": [
    "widget.taskf0000detail"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Zixweb.controller.Roles": [],
  "Zixweb.controller.Yspz": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Zixweb.view.zjdz.bfj": [
    "widget.zjdzbfj"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Zixweb.store.fhw_type": [],
  "overrides.panel.Panel": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.DataView.Animated": [],
  "overrides.DateField": [],
  "Zixweb.view.component.hsx.e_date": [
    "widget.e_date"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Zixweb.view.component.ts_revoke": [
    "widget.ts_revoke"
  ],
  "Zixweb.view.component.hsx.zjbd_date": [
    "widget.zjbd_date"
  ],
  "Zixweb.controller.Books": [],
  "Zixweb.store.p": [],
  "Zixweb.view.book.AllBooks": [
    "widget.bookall"
  ],
  "Zixweb.view.component.hsx.tx_date": [
    "widget.tx_date"
  ],
  "Zixweb.view.Panel": [],
  "Zixweb.view.component.hsx.fch": [
    "widget.fch"
  ],
  "Ext.ux.event.Player": [],
  "overrides.Connection": [],
  "Ext.ux.ToolbarDroppable": [],
  "Zixweb.view.zjdz.bfjdetail": [
    "widget.zjdzbfjdetail"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Zixweb.view.pzlr.i0101": [
    "widget.i0101"
  ],
  "Zixweb.view.book.BookPanel": [],
  "Zixweb.view.component.hsx.bfj_acct": [
    "widget.bfj_acct",
    "widget.bfjacct"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Zixweb.view.jcsjwh.bfjacct.List": [
    "widget.bfjacctlist"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "overrides.HBox": [],
  "overrides.tab.Tab": [],
  "overrides.grid.RowEditor": [],
  "overrides.Treepanel": [],
  "Zixweb.view.task.TaskFmy": [
    "widget.taskfmy"
  ],
  "Zixweb.view.component.base.Money": [
    "widget.money"
  ],
  "Zixweb.view.Viewport": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Zixweb.view.component.hsx.bi": [
    "widget.bi"
  ],
  "Zixweb.view.jcsjwh.bfjacct.Add": [
    "widget.bfjacctadd"
  ],
  "Zixweb.view.pzlr.i0000": [
    "widget.i0000"
  ],
  "Zixweb.view.component.Routes": [
    "widget.routes"
  ],
  "Zixweb.controller.Index": [],
  "Zixweb.view.component.Fields": [
    "widget.tablefields"
  ],
  "Zixweb.controller.Task": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Zixweb.view.pzlr.i0149": [
    "widget.i0149"
  ],
  "Zixweb.store.wlzj_type": [],
  "Zixweb.view.pzlr.i0148": [
    "widget.i0148"
  ],
  "Zixweb.store.CBase": [],
  "Zixweb.view.component.hsx.period": [
    "widget.period"
  ],
  "Zixweb.view.component.base.TextField": [],
  "Zixweb.controller.Login": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Zixweb.view.component.base.DateField": [],
  "Zixweb.view.Center": [
    "widget.center"
  ],
  "Zixweb.view.user.Add": [
    "widget.useradd"
  ],
  "Zixweb.store.zyzj_acct": [],
  "Zixweb.view.component.hsx.fhw_type": [
    "widget.fhw_type"
  ],
  "Zixweb.view.component.SHType": [
    "widget.shtype"
  ],
  "overrides.toolbar.Paging": [],
  "Zixweb.view.component.hsx.fcg_date": [
    "widget.fcg_date"
  ],
  "Zixweb.view.pzlr.mission": [
    "widget.pzlrmission"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Zixweb.view.component.YSID": [
    "widget.ysidfield"
  ],
  "Zixweb.view.yspz.Detail": [
    "widget.yspzqdetail"
  ],
  "overrides.resizer.Splitter": [],
  "overrides.Component": [],
  "overrides.TabCloseMenu": [],
  "Zixweb.view.pzlr.f0000": [
    "widget.f0000"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Zixweb.view.component.hsx.f_agm": [
    "widget.f_agm"
  ],
  "Zixweb.store.MStatus": [],
  "Zixweb.view.user.List": [
    "widget.userlist"
  ],
  "Zixweb.store.Status": [],
  "Zixweb.view.login.PasswordReset": [
    "widget.passwordreset"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Zixweb.view.zjdz.qddetail": [
    "widget.zjdzqddetail"
  ],
  "Zixweb.controller.Routes": [],
  "Zixweb.view.component.revoke_user": [
    "widget.revoke_user"
  ],
  "Zixweb.view.component.MStatus": [
    "widget.mstatus"
  ],
  "overrides.Date": [],
  "Zixweb.view.component.base.QueryForm": [
    "widget.queryform"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Zixweb.view.pzlr.i0015": [
    "widget.i0015"
  ],
  "Zixweb.view.pzlr.i0014": [
    "widget.i0014"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Zixweb.view.component.base.MoneyField": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Zixweb.store.fyw_type": [],
  "Zixweb.view.component.hsx.acct": [
    "widget.acct"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Zixweb.view.pzlr.i0018": [
    "widget.i0018"
  ],
  "overrides.toolbar.Toolbar": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Zixweb.view.component.hsx.fm": [
    "widget.fm"
  ],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Zixweb.view.component.hsx.zjbd_type": [
    "widget.zjbd_type",
    "widget.zjbdtype"
  ],
  "overrides.form.field.HtmlEditor": [],
  "Zixweb.view.component.hsx.fc": [
    "widget.fc"
  ],
  "Zixweb.store.YsType": [],
  "Zixweb.view.task.TaskFpzcxdetail": [
    "widget.taskfpzcxdetail"
  ],
  "Zixweb.view.zjdz.qd": [
    "widget.zjdzqd"
  ],
  "Zixweb.view.West": [
    "widget.west"
  ],
  "Zixweb.view.role.Edit": [
    "widget.roledit"
  ],
  "Zixweb.store.bi": [],
  "Zixweb.view.component.SHStatus": [
    "widget.shstatus"
  ],
  "Zixweb.view.zjdz.bfjgzcx": [
    "widget.zjdzbfjgzcx"
  ],
  "Zixweb.view.component.ExportBtn": [
    "widget.exportbtn"
  ],
  "Zixweb.view.component.base.MyStore": [
    "widget.mystore"
  ],
  "Zixweb.view.component.hsx.wlzj_type": [
    "widget.wlzj_type",
    "widget.wlzjtype"
  ],
  "Zixweb.view.book.BfjBooks": [
    "widget.bookbfj"
  ],
  "Zixweb.view.role.Add": [
    "widget.roleadd"
  ],
  "Zixweb.view.zqqr.submit": [
    "widget.zqqrsubmit"
  ],
  "Zixweb.view.task.Task0000": [
    "widget.task0000"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Zixweb.controller.Jcsjwh": [],
  "Zixweb.view.book.FhydBooks": [
    "widget.bookfhyd"
  ],
  "Zixweb.Application": [],
  "Zixweb.view.zjdz.bfjresult": [
    "widget.zjdzbfjresult"
  ],
  "Zixweb.view.component.hsx.p": [
    "widget.p",
    "widget.product"
  ],
  "Zixweb.view.book.DetailPanel": [],
  "overrides.container.ButtonGroup": [],
  "overrides.panel.Tool": [],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Zixweb.view.component.ID": [
    "widget.idfield"
  ],
  "Ext.ux.RowExpander": [],
  "Zixweb.store.zjbd_type": [],
  "Zixweb.view.component.hsx.c": [
    "widget.c"
  ],
  "Zixweb.controller.Zjdz": [],
  "Zixweb.view.component.base.ComboBox": [],
  "Zixweb.view.North": [
    "widget.north"
  ],
  "overrides.menu.Menu": [],
  "Zixweb.view.task.Taskpzcxdetail": [
    "widget.taskpzcxdetail"
  ],
  "Zixweb.view.component.plugins.PageComboResizer": [],
  "Zixweb.store.bfj_acct": [],
  "Ext.ux.event.Maker": [],
  "Zixweb.view.component.hsx.f_dcn": [
    "widget.f_dcn"
  ],
  "Zixweb.view.task.Task0000detail": [
    "widget.task0000detail"
  ],
  "overrides.menu.Separator": [],
  "Zixweb.view.component.hsx.fhyd_acct": [
    "widget.fhyd_acct"
  ],
  "Zixweb.controller.Zqqr": [],
  "overrides.picker.Month": [],
  "overrides.VType": [],
  "Zixweb.view.book.SumPanel": [],
  "Zixweb.view.component.crt_user": [
    "widget.crt_user"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Zixweb.view.component.ZQQRStatus": [
    "widget.zqqrstatus"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Zixweb.view.component.hsx.fp": [
    "widget.fp"
  ],
  "Zixweb.view.task.Taskpzcx": [
    "widget.taskpzcx"
  ],
  "Zixweb.view.component.hsx.cust_proto": [
    "widget.cust_proto"
  ]
});
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/layout/component/Dock.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/Component.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/panel/Panel.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/toolbar/Toolbar.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/container/ButtonGroup.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/toolbar/Paging.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/picker/Month.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/form/field/HtmlEditor.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/panel/Table.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/grid/RowEditor.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/grid/column/RowNumberer.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/resizer/Splitter.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/menu/Menu.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/menu/Separator.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/panel/Tool.js");
Ext.Loader.loadScript("../packages/my-custom-theme/overrides/tab/Tab.js");
