Ext.define('Zixweb.controller.Books', {
			extend : 'Ext.app.Controller',
			views : ['book.AllBooks', 'book.ZyzjBooks', 'book.BfjBooks',
					'book.FhydBooks', 'book.detail.deposit_bfj',
					'book.hist.deposit_bfj', 'book.detail.income_cfee',
					'book.hist.income_cfee', 'book.detail.income_in',
					'book.hist.income_in', 'book.detail.cost_bfee',
					'book.hist.cost_bfee', 'book.detail.cost_dfss',
					'book.hist.cost_dfss', 'book.detail.cost_bfee_zg',
					'book.hist.cost_bfee_zg', 'book.detail.cost_in',
					'book.hist.cost_in', 'book.detail.income_zhlx',
					'book.hist.income_zhlx', 'book.detail.fee_jrjg',
					'book.hist.fee_jrjg', 'book.detail.txamt_yhyf',
					'book.hist.txamt_yhyf', 'book.detail.bamt_yhyf',
					'book.hist.bamt_yhyf', 'book.detail.bfee_yhyf',
					'book.hist.bfee_yhyf', 'book.detail.txamt_dqr_byf',
					'book.hist.txamt_dqr_byf', 'book.detail.bfj_cust',
					'book.hist.bfj_cust', 'book.detail.deposit_zyzj',
					'book.hist.deposit_zyzj', 'book.detail.txamt_dgd',
					'book.hist.txamt_dgd', 'book.detail.txamt_yhys',
					'book.hist.txamt_yhys', 'book.detail.bamt_yhys',
					'book.hist.bamt_yhys', 'book.detail.bfee_yhys',
					'book.hist.bfee_yhys', 'book.detail.blc', 'book.hist.blc',
					'book.detail.blc_zyzj', 'book.hist.blc_zyzj',
					'book.detail.bfee_cwwf', 'book.hist.bfee_cwwf',
					'book.detail.bfee_zqqr_zg', 'book.hist.bfee_zqqr_zg',
					'book.detail.bfee_zqqr', 'book.hist.bfee_zqqr',
					'book.detail.txamt_dqr_oyf', 'book.hist.txamt_dqr_oyf',
					'book.detail.deposit_bfj', 'book.hist.deposit_bfj',
					'book.detail.deposit_bfj', 'book.hist.deposit_bfj',
					'book.detail.cfee_dqhf', 'book.hist.cfee_dqhf',
					'book.detail.lfee_psp', 'book.hist.lfee_psp',
					'book.detail.bsc', 'book.hist.bsc', 'book.detail.bsc_zyzj',
					'book.hist.bsc_zyzj', 'book.detail.bfee_rb',
					'book.hist.bfee_rb', 'book.detail.txamt_dqr_oys',
					'book.hist.txamt_dqr_oys', 'book.detail.wlzj_ysbf',
					'book.hist.wlzj_ysbf', 'book.detail.wlzj_yszy',
					'book.hist.wlzj_yszy', 'book.detail.wlzj_yfbf',
					'book.hist.wlzj_yfbf', 'book.detail.wlzj_yfzy',
					'book.hist.wlzj_yfzy', 
                    'book.detail.ckrsp_fhyd', 'book.hist.ckrsp_fhyd',
                    'book.detail.yplc_fhyd', 'book.hist.yplc_fhyd',
                    'book.detail.yfamt_m_fhyd', 'book.hist.yfamt_m_fhyd',
                    'book.detail.chamt_dgd_fhyd', 'book.hist.chamt_dgd_fhyd',
                    'book.detail.yfamt_ch_fhyd', 'book.hist.yfamt_ch_fhyd',
                    'book.detail.yfamt_dcch_fhyd', 'book.hist.yfamt_dcch_fhyd',
                    'book.detail.yusamt_c_fhyd', 'book.hist.yusamt_c_fhyd',
                    'book.detail.nctxamt_dqr_oyf_fhyd', 'book.hist.nctxamt_dqr_oyf_fhyd',
                    'book.detail.tctxamt_dqr_oyf_fhyd', 'book.hist.tctxamt_dqr_oyf_fhyd',
                    'book.detail.cost_tcss_fhyd', 'book.hist.cost_tcss_fhyd',
                    'book.detail.cost_dcch_fhyd', 'book.hist.cost_dcch_fhyd']
		});
