Ext.define('Zixweb.controller.Component', {
			extend : 'Ext.app.Controller',
			stores : [/* 转义用数据集基类 */'component.CBase', 'component.Acct',
					'component.BfjAcct', 'component.Bi', 'component.ZyzjAcct',
					'component.Status', 'component.RStatus',
					'component.MStatus', 'component.JStatus',
					'component.ZjbdType', 'component.Product',
					'component.YsType', 'component.ZQQRStatus',
					'component.WlzjType', 'component.FhwType',
					'component.FypAcct', 'component.FhydAcct',
					'component.FywType'],
			views : ['component.Acct', 'component.BfjAcct', 'component.Bi',
					'component.ZyzjAcct', 'component.Status',
					'component.RStatus', 'component.MStatus',
					'component.ZjbdType', 'component.SHStatus',
					'component.SHType', 'component.Books', 'component.Product',
					'component.YsType', 'component.ZQQRStatus',
					'component.HSX', 'component.WlzjType', 'component.FhwType',
					'component.FypAcct', 'component.FhydAcct',
					'component.FywType', 'component.YsTypeF',
					'component.plugins.PageComboResizer', 'component.Money',
					'component.Fields', 'component.AcctStatus',
					'component.ExportBtn', 'component.MyStore',
					'component.QueryForm', 'component.Period', 'component.Fch']

		});